server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: REPORTS
          uri: lb://reports
          predicates:
            - Path=/reports/**
          order: 1

        - id: USERS
          uri: lb://users
          predicates:
            - Path=/users/**
          order: 2

        - id: AUTH
          uri: lb://users
          predicates:
            - Path=/auth/**
          order: 3

        - id: static_resources
          uri: forward:/static
          predicates:
            - Path=/static/**
          order: 4

        - id: spa_fallback
          uri: forward:/index.html
          predicates:
            - Path=/**
          order: 5

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allow-credentials: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/