server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: REPORTS
          uri: http://localhost:8081
          predicates:
            - Path=/reports/**
        - id: USERS
          uri: http://localhost:8075
          predicates:
            - Path=/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/